### ISSUE TITLE
Fixed wing dubins path following

### ISSUE THREAD

**Issue by bradygm** [castacks/onr_meta#315]

**Comment by andrewjong** [comment]
Actually nah, just make the turning radius fast and the scale big, then fixed wing dubins is approximate enough

**Comment by andrewjong** [comment]
Update: actually we may need this because our Simple IPP Sim doesn't follow the dubins path properly. That means the frustums that it expects to see are sometimes rotated totally off of what the sim is capable of showing. Could either improve the dubins point following in our sim, similar to how JHU does, or change the paths to quad motion model

**Comment by andrewjong** [comment]
done
